author:
  - name: "Lars Höft"
    corresponding: true
    orcid: 0000-0002-9040-8995
    email: hoeft@leibniz-ipn.de
    affiliations:
      - id: id1
        name: IPN - Leibniz Institute for Science and Mathematics Education
        address: Olshausenstraße 62
        city: Kiel
        state: SH
        postal-code: "24114"
        country: Germany
  - name: "Jennifer Meyer"
    orcid: 0000-0002-5714-3198
    email: jmeyer@leibniz-ipn.de
    affiliations:
      - ref: id1
      - id: id2
        name: University of Vienna, Centre for Teacher Education
        address: Porzellangasse 4
        city: Wien
        state: Wien
        postal-code: "1090"
        country: Austria
  - name: "Sascha Bernholt"
    email: bernholt@leibniz-ipn.de
    orcid: 0000-0003-4045-3795
    affiliations:
      - ref: id1
  - name: "Thorben Jansen"
    orcid: 0000-0001-9714-6505
    email: tjansen@leibniz-ipn.de
    affiliations:
      - ref: id1
